import Head from 'next/head'
import React, { useState, useEffect, useRef } from 'react';
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { PieButton } from '@justeattakeaway/pie-button/dist/react';
import { PieModal } from '@justeattakeaway/pie-modal/dist/react';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const myRef = useRef<HTMLElement | null>(null);

  const [isModalOpen, setIsModalOpen] = useState(false);
  const toggleModal = () => setIsModalOpen(!isModalOpen);

  useEffect(() => {
    const handleModalCloseEvent = () => {
      setIsModalOpen(false);
    }

    const currentElement = myRef.current;
    if(currentElement) {
      currentElement.addEventListener('pie-modal-close', handleModalCloseEvent as EventListener);

      return () => {
        currentElement.removeEventListener('pie-modal-close', handleModalCloseEvent as EventListener);
      }
    }

  }, []);

  const [count, setCount] = useState(0);
  const increment = () => setCount(count + 1);
  const decrement = () => setCount(count - 1);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <h1 className={styles.title}>PIE Integration: NextJS</h1>

        <p>This is an example app that integrates PIE web components in to NextJS 13</p>
        <p>The required dependencies are:</p>
        <ul>
          <li>@justeattakeaway/pie-button</li>
          <li>@justeattakeaway/pie-modal</li>
          <li>@justeat/pie-design-tokens</li>
          <li>lit</li>
          <li>@lit-labs/nextjs</li>
          <li>@lit-labs/react</li>
        </ul>

        <PieButton onClick={toggleModal}>Open the counter controls</PieButton>
        <PieModal
          ref={myRef}
          isOpen={isModalOpen}
          heading="Lit AF"
          headingLevel="h2"
          isDismissible={true}
          isFullWidthBelowMid={true}
          size="large">
            <div className={styles.modalInner}>
              <p>Use the controls to increment and decrement the counter :)</p>
              <p>Counter: { count }</p>
              <PieButton size="xsmall" onClick={increment}>Increment</PieButton>
              <PieButton size="xsmall" onClick={decrement}>Decrement</PieButton>
            </div>
        </PieModal>
      </main>
    </>
  )
}
