import Head from 'next/head'
import React, { useState, useEffect, useRef } from 'react';
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { PieButton } from '@justeattakeaway/pie-button/dist/react';
import { PieModal } from '@justeattakeaway/pie-modal/dist/react';


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const myRef = useRef<HTMLElement | null>(null);

  const [isModalOpen, setIsModalOpen] = useState(false);
  const toggleModal = () => setIsModalOpen(!isModalOpen);

  useEffect(() => {
    const handleModalCloseEvent = () => {
      setIsModalOpen(false);
    }

    const currentElement = myRef.current;
    if(currentElement) {
      currentElement.addEventListener('pie-modal-close', handleModalCloseEvent as EventListener);

      return () => {
        currentElement.removeEventListener('pie-modal-close', handleModalCloseEvent as EventListener);
      }
    }

  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <PieButton onClick={toggleModal}>Hello, Clarice</PieButton>
        <PieModal
          ref={myRef}
          isOpen={isModalOpen}
          heading="Lit AF"
          headingLevel="h2"
          isDismissible={true}
          isFullWidthBelowMid={true}
          size="large">
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Enim maxime, magnam totam officiis earum praesentium quos, necessitatibus reprehenderit vitae, quas sit! Modi nemo voluptatibus quaerat odio tenetur ea, accusantium quis!</p>
        </PieModal>
      </main>
    </>
  )
}
